### ISSUE TITLE
Open Sourcing AHS 

### ISSUE THREAD

**Issue by ecedmondson** [americanhandelsociety/americanhandelsociety-members#155]
# WIP

Issue to track items needing prioritization for open sourcing the project.

**Comment by reginafcompton** [comment]
Tis done.

**Comment by ecedmondson** [comment]
<img width="750" alt="Screen Shot 2023-04-24 at 12 28 01 PM" src="https://user-images.githubusercontent.com/29210441/234071811-23013b5a-abc1-4f02-b80d-7fa5a6528459.png">
Great news!
