### ISSUE TITLE
[Admin table] Clearly expose information about which members have paid their dues for the year

### ISSUE THREAD

**Issue by reginafcompton** [americanhandelsociety/americanhandelsociety-members#171]

**Comment by ecedmondson** [comment]
I saw a merge come in and decided to come look at issues. Does this still need to be done? I saw two others that seem recent, but both require access to things/people I do not have access to.

**Comment by reginafcompton** [comment]
Hello!

The AHS board met today...and a few requests came in. I tracked them here: https://github.com/orgs/americanhandelsociety/projects/2/views/1

Do you have any interest in tackling the email revision? I expect it will be fairly quick....but also: emails. (I know.)
