### ISSUE TITLE
Expose the membership type and “life” members in the admin dashboard

### ISSUE THREAD

**Issue by reginafcompton** [americanhandelsociety/americanhandelsociety-members#178]
Expose the membership type and “Life” members in the admin dashboard.

**Comment by ecedmondson** [comment]
Hello @reginafcompton. Do you mind if I pick up this issue (or perhaps another)?

**Comment by reginafcompton** [comment]
Yep – that would be super! 

Alternatively, you could take this issue: https://github.com/americanhandelsociety/americanhandelsociety-members/issues/171 (which seems like a reasonable follow-up to the email work). Thanks.
